### ISSUE TITLE
任务结束后，任务状态还是运行中

### ISSUE THREAD

**Issue by Dlian-Zero** [ilusrdbb/lightnovel-sign#1]
![image](https://github.com/ilusrdbb/lightnovel-sign/assets/52018129/45942ffe-c22d-45e5-adb5-780a344f89cb)
使用的是青龙面板，每天定时运行，但是状态一直是运行中，能否加个完成自动结束，还有可不可以搞个通知，感谢大佬

**Comment by ilusrdbb** [comment]
没想到有人用这东西，，，
暂时不考虑对接青龙面板，建议安装python环境后直接运行
关于通知日后有空再开发吧
